### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Joe Green",
  "email": "joe@example.com",
  "password": "joe",
  "password_confirmation": "joe"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "joe@example.com",
  "password": "joe"
}

### Photos create
GET http://localhost:3000/users.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUzODIzNjR9.CNjFgQOUiqN3XYbW_jKydMP5JACc6u53BN7SNeHao1Q
Content-Type: application/json

